service: wami-backend-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-2

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
