service: wami-backend-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  environment:
    CHALLENGES_TABLE_NAME: ${self:custom.ChallengesTable.name}
  iamRoleStatements:
    - ${file(iam/ChallengesTableIAM.yml):ChallengesTableIAM}

resources:
  Resources:
    ChallengesTable: ${file(resources/ChallengesTable.yml):ChallengesTable}

functions:
  challenge:
    handler: functions/challenge/handler.handler
    events:
      - http:
          path: challenge
          method: get
      - http:
          path: challenge
          method: post

custom:
  ChallengesTable:
    name: !Ref ChallengesTable
    arn: !GetAtt ChallengesTable.Arn
