ChallengesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ChallengesTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: date
        AttributeType: N
    KeySchema:
      - AttributeName: date
        KeyType: HASH
